package com.demo.shawn.newsapp.data.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.demo.shawn.newsapp.data.bean.User;
import com.demo.shawn.newsapp.data.bean.NewsChannel;

import com.demo.shawn.newsapp.data.db.UserDao;
import com.demo.shawn.newsapp.data.db.NewsChannelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig newsChannelDaoConfig;

    private final UserDao userDao;
    private final NewsChannelDao newsChannelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        newsChannelDaoConfig = daoConfigMap.get(NewsChannelDao.class).clone();
        newsChannelDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        newsChannelDao = new NewsChannelDao(newsChannelDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(NewsChannel.class, newsChannelDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        newsChannelDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public NewsChannelDao getNewsChannelDao() {
        return newsChannelDao;
    }

}
